name: glew
description: A Dart library for accessing common glew APIs using, FFI.
version: 1.1.0
homepage: https://github.com/sansuido/glew
repository: https://github.com/sansuido/glew

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  glfw3: ^1.1.2
  image: ^4.0.13
  sdl2: ^1.5.2
  vector_math: ^2.1.4
  change_case: ^1.0.2


