name: glew
description: A Dart library for accessing common glew APIs using, FFI.
version: 1.0.2
homepage: https://github.com/sansuido/glew
repository: https://github.com/sansuido/glew

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  glfw3: ^1.0.0
  image: ^3.0.2
  sdl2: ^1.0.12
  vector_math: ^2.1.0

