name: glew
description: A Dart library for accessing common glew APIs using, FFI.
version: 1.2.0
homepage: https://github.com/sansuido/glew
repository: https://github.com/sansuido/glew

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  glfw3: ^1.2.0
  change_case: ^2.0.1


